### ISSUE TITLE
warning "array_key_exists() expects parameter 2 to be array, null given" when creating poll

### ISSUE THREAD

**Issue by svigerske** [humhub/humhub-modules-polls#39]
With HumHub 1.2.4 and Polls plugin 0.9.10, a user got the following PHP warning:
```
{
    "url": "/s/general/polls/poll/create",
    "status": 500,
    "response": {
        "name": "PHP Warning",
        "message": "array_key_exists() expects parameter 2 to be
array, null given",
        "code": 2,
        "type": "yii\\base\\ErrorException",
        "file": "/var/www/humhub/protected/modules/polls/models/Poll.php",
        "line": 187,
        "stack-trace": [
            "#0 [internal function]:
yii\\base\\ErrorHandler->handleError(2, 'array_key_exist...',
'/var/www/humhub...', 187, Array)",
            "#1
/var/www/humhub/protected/modules/polls/models/Poll.php(187):
array_key_exists(202, NULL)",
            "#2
/var/www/humhub/protected/modules/polls/models/Poll.php(145):
humhub\\modules\\polls\\models\\Poll->updateAnswers()",
            "#3
/var/www/humhub/protected/vendor/yiisoft/yii2/db/BaseActiveRecord.php(789):
humhub\\modules\\polls\\models\\Poll->afterSave(false, Array)",
            "#4
/var/www/humhub/protected/vendor/yiisoft/yii2/db/ActiveRecord.php(570):
yii\\db\\BaseActiveRecord->updateInternal(NULL)",
            "#5
/var/www/humhub/protected/vendor/yiisoft/yii2/db/BaseActiveRecord.php(645):
yii\\db\\ActiveRecord->update(true, NULL)",
            "#6
/var/www/humhub/protected/humhub/modules/file/components/FileManager.php(70):
yii\\db\\BaseActiveRecord->save()",
            "#7
/var/www/humhub/protected/humhub/modules/content/widgets/WallCreateContentForm.php(140):
humhub\\modules\\file\\components\\FileManager->attach(Array)",
            "#8
/var/www/humhub/protected/modules/polls/controllers/PollController.php(64):
humhub\\modules\\content\\widgets\\WallCreateContentForm::create(Object(humhub\\modules\\polls\\models\\Poll),
Object(humhub\\modules\\space\\models\\Space))",
            "#9 [internal function]:
humhub\\modules\\polls\\controllers\\PollController->actionCreate()",
            "#10
/var/www/humhub/protected/vendor/yiisoft/yii2/base/InlineAction.php(57):
call_user_func_array(Array, Array)",
            "#11
/var/www/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(156):
yii\\base\\InlineAction->runWithParams(Array)",
            "#12
/var/www/humhub/protected/vendor/yiisoft/yii2/base/Module.php(523):
yii\\base\\Controller->runAction('create', Array)",
            "#13
/var/www/humhub/protected/vendor/yiisoft/yii2/web/Application.php(102):
yii\\base\\Module->runAction('polls/poll/crea...', Array)",
            "#14
/var/www/humhub/protected/vendor/yiisoft/yii2/base/Application.php(380):
yii\\web\\Application->handleRequest(Object(humhub\\components\\Request))",
            "#15 /var/www/humhub/index.php(25): yii\\base\\Application->run()",
            "#16 {main}"
        ]
    },
    "textStatus": "error",
    "dataType": "json",
    "xhr": {
        "readyState": 4,
        "responseText": "{\"name\":\"PHP
Warning\",\"message\":\"array_key_exists() expects parameter 2 to be
array, null given\",\"code\":2,\"type\":\"yii\\\\base\\\\ErrorException\",\"file\":\"/var/www/humhub/protected/modules/polls/models/Poll.php\",\"line\":187,\"stack-trace\":[\"#0
[internal function]: yii\\\\base\\\\ErrorHandler->handleError(2,
'array_key_exist...', '/var/www/humhub...', 187, Array)\",\"#1
/var/www/humhub/protected/modules/polls/models/Poll.php(187):
array_key_exists(202, NULL)\",\"#2
/var/www/humhub/protected/modules/polls/models/Poll.php(145):
humhub\\\\modules\\\\polls\\\\models\\\\Poll->updateAnswers()\",\"#3
/var/www/humhub/protected/vendor/yiisoft/yii2/db/BaseActiveRecord.php(789):
humhub\\\\modules\\\\polls\\\\models\\\\Poll->afterSave(false,
Array)\",\"#4 /var/www/humhub/protected/vendor/yiisoft/yii2/db/ActiveRecord.php(570):
yii\\\\db\\\\BaseActiveRecord->updateInternal(NULL)\",\"#5
/var/www/humhub/protected/vendor/yiisoft/yii2/db/BaseActiveRecord.php(645):
yii\\\\db\\\\ActiveRecord->update(true, NULL)\",\"#6
/var/www/humhub/protected/humhub/modules/file/components/FileManager.php(70):
yii\\\\db\\\\BaseActiveRecord->save()\",\"#7
/var/www/humhub/protected/humhub/modules/content/widgets/WallCreateContentForm.php(140):
humhub\\\\modules\\\\file\\\\components\\\\FileManager->attach(Array)\",\"#8
/var/www/humhub/protected/modules/polls/controllers/PollController.php(64):
humhub\\\\modules\\\\content\\\\widgets\\\\WallCreateContentForm::create(Object(humhub\\\\modules\\\\polls\\\\models\\\\Poll),
Object(humhub\\\\modules\\\\space\\\\models\\\\Space))\",\"#9
[internal function]:
humhub\\\\modules\\\\polls\\\\controllers\\\\PollController->actionCreate()\",\"#10
/var/www/humhub/protected/vendor/yiisoft/yii2/base/InlineAction.php(57):
call_user_func_array(Array, Array)\",\"#11
/var/www/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(156):
yii\\\\base\\\\InlineAction->runWithParams(Array)\",\"#12
/var/www/humhub/protected/vendor/yiisoft/yii2/base/Module.php(523):
yii\\\\base\\\\Controller->runAction('create', Array)\",\"#13
/var/www/humhub/protected/vendor/yiisoft/yii2/web/Application.php(102):
yii\\\\base\\\\Module->runAction('polls/poll/crea...', Array)\",\"#14
/var/www/humhub/protected/vendor/yiisoft/yii2/base/Application.php(380):
yii\\\\web\\\\Application->handleRequest(Object(humhub\\\\components\\\\Request))\",\"#15
/var/www/humhub/index.php(25):
yii\\\\base\\\\Application->run()\",\"#16 {main}\"]}",
        "responseJSON": {
            "name": "PHP Warning",
            "message": "array_key_exists() expects parameter 2 to be
array, null given",
            "code": 2,
            "type": "yii\\base\\ErrorException",
            "file": "/var/www/humhub/protected/modules/polls/models/Poll.php",
            "line": 187,
            "stack-trace": [
                "#0 [internal function]:
yii\\base\\ErrorHandler->handleError(2, 'array_key_exist...',
'/var/www/humhub...', 187, Array)",
                "#1
/var/www/humhub/protected/modules/polls/models/Poll.php(187):
array_key_exists(202, NULL)",
                "#2
/var/www/humhub/protected/modules/polls/models/Poll.php(145):
humhub\\modules\\polls\\models\\Poll->updateAnswers()",
                "#3
/var/www/humhub/protected/vendor/yiisoft/yii2/db/BaseActiveRecord.php(789):
humhub\\modules\\polls\\models\\Poll->afterSave(false, Array)",
                "#4
/var/www/humhub/protected/vendor/yiisoft/yii2/db/ActiveRecord.php(570):
yii\\db\\BaseActiveRecord->updateInternal(NULL)",
                "#5
/var/www/humhub/protected/vendor/yiisoft/yii2/db/BaseActiveRecord.php(645):
yii\\db\\ActiveRecord->update(true, NULL)",
                "#6
/var/www/humhub/protected/humhub/modules/file/components/FileManager.php(70):
yii\\db\\BaseActiveRecord->save()",
                "#7
/var/www/humhub/protected/humhub/modules/content/widgets/WallCreateContentForm.php(140):
humhub\\modules\\file\\components\\FileManager->attach(Array)",
                "#8
/var/www/humhub/protected/modules/polls/controllers/PollController.php(64):
humhub\\modules\\content\\widgets\\WallCreateContentForm::create(Object(humhub\\modules\\polls\\models\\Poll),
Object(humhub\\modules\\space\\models\\Space))",
                "#9 [internal function]:
humhub\\modules\\polls\\controllers\\PollController->actionCreate()",
                "#10
/var/www/humhub/protected/vendor/yiisoft/yii2/base/InlineAction.php(57):
call_user_func_array(Array, Array)",
                "#11
/var/www/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(156):
yii\\base\\InlineAction->runWithParams(Array)",
                "#12
/var/www/humhub/protected/vendor/yiisoft/yii2/base/Module.php(523):
yii\\base\\Controller->runAction('create', Array)",
                "#13
/var/www/humhub/protected/vendor/yiisoft/yii2/web/Application.php(102):
yii\\base\\Module->runAction('polls/poll/crea...', Array)",
                "#14
/var/www/humhub/protected/vendor/yiisoft/yii2/base/Application.php(380):
yii\\web\\Application->handleRequest(Object(humhub\\components\\Request))",
                "#15 /var/www/humhub/index.php(25):
yii\\base\\Application->run()",
                "#16 {main}"
            ]
        },
        "status": 500,
        "statusText": "Internal Server Error"
    },
    "name": "PHP Warning",
    "message": "array_key_exists() expects parameter 2 to be array, null given",
    "code": 2,
    "type": "yii\\base\\ErrorException",
    "file": "/var/www/humhub/protected/modules/polls/models/Poll.php",
    "line": 187,
    "stack-trace": [
        "#0 [internal function]:
yii\\base\\ErrorHandler->handleError(2, 'array_key_exist...',
'/var/www/humhub...', 187, Array)",
        "#1 /var/www/humhub/protected/modules/polls/models/Poll.php(187):
array_key_exists(202, NULL)",
        "#2 /var/www/humhub/protected/modules/polls/models/Poll.php(145):
humhub\\modules\\polls\\models\\Poll->updateAnswers()",
        "#3 /var/www/humhub/protected/vendor/yiisoft/yii2/db/BaseActiveRecord.php(789):
humhub\\modules\\polls\\models\\Poll->afterSave(false, Array)",
        "#4 /var/www/humhub/protected/vendor/yiisoft/yii2/db/ActiveRecord.php(570):
yii\\db\\BaseActiveRecord->updateInternal(NULL)",
        "#5 /var/www/humhub/protected/vendor/yiisoft/yii2/db/BaseActiveRecord.php(645):
yii\\db\\ActiveRecord->update(true, NULL)",
        "#6 /var/www/humhub/protected/humhub/modules/file/components/FileManager.php(70):
yii\\db\\BaseActiveRecord->save()",
        "#7 /var/www/humhub/protected/humhub/modules/content/widgets/WallCreateContentForm.php(140):
humhub\\modules\\file\\components\\FileManager->attach(Array)",
        "#8 /var/www/humhub/protected/modules/polls/controllers/PollController.php(64):
humhub\\modules\\content\\widgets\\WallCreateContentForm::create(Object(humhub\\modules\\polls\\models\\Poll),
Object(humhub\\modules\\space\\models\\Space))",
        "#9 [internal function]:
humhub\\modules\\polls\\controllers\\PollController->actionCreate()",
        "#10 /var/www/humhub/protected/vendor/yiisoft/yii2/base/InlineAction.php(57):
call_user_func_array(Array, Array)",
        "#11 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(156):
yii\\base\\InlineAction->runWithParams(Array)",
        "#12 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Module.php(523):
yii\\base\\Controller->runAction('create', Array)",
        "#13 /var/www/humhub/protected/vendor/yiisoft/yii2/web/Application.php(102):
yii\\base\\Module->runAction('polls/poll/crea...', Array)",
        "#14 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Application.php(380):
yii\\web\\Application->handleRequest(Object(humhub\\components\\Request))",
        "#15 /var/www/humhub/index.php(25): yii\\base\\Application->run()",
        "#16 {main}"
    ],
    "error": {},
    "errorThrown": "Internal Server Error",
    "validationError": false
}
```
I see that I accidentally left Humhub in debugging mode. Don't know if that is related.

**Comment by aboettger-tuhh** [comment]
same problem here

**Comment by Richies97** [comment]
Get the same problem, but this problem only occurs when i attach a file to the poll. Is there a solution?
